name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate self-signed TLS cert for CI
        run: |
          mkdir -p artifacts/cert
          openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
            -keyout artifacts/cert/server.key \
            -out artifacts/cert/server.crt \
            -subj "/CN=localhost"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t nodegoat:ci .

        
  sast-semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --error --severity ERROR .